package com.personal.ecommercesys.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName cropsinfo
 */
@Data
public class Cropsinfo implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:31 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private String name;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private Double unit;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private Double sales;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private Double repertory;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private String detailinfo;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private String seller;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private String picturelocation;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private Date addingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cropsinfo
     *
     * @mbg.generated Sat Jan 09 17:57:32 CST 2021
     */
    private static final long serialVersionUID = 1L;
}