package com.personal.ecommercesys.model;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName useridentifyid
 */
@Data
public class Useridentifyid implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue May 04 17:26:13 CST 2021
     */
    private String id;

    /**
     * 
     *
     * @mbg.generated Tue May 04 17:26:13 CST 2021
     */
    private String realname;

    /**
     * 
     *
     * @mbg.generated Tue May 04 17:26:13 CST 2021
     */
    private String idcardfront;

    /**
     * 
     *
     * @mbg.generated Tue May 04 17:26:13 CST 2021
     */
    private String idcardbehind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table useridentifyid
     *
     * @mbg.generated Tue May 04 17:26:13 CST 2021
     */
    private static final long serialVersionUID = 1L;
}