package com.personal.ecommercesys.model;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @TableName userinfo
 */
@Data
@NoArgsConstructor // 默认构造
@AllArgsConstructor
public class Userinfo implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String gender;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String userpwd;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String telephone;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String address;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String grade;

    /**
     * 
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private String identitycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated Sun Jan 03 18:33:25 CST 2021
     */
    private static final long serialVersionUID = 1L;

}