package com.personal.ecommercesys.model;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @TableName usershopcart
 */
@Data
@NoArgsConstructor // 默认构造
@AllArgsConstructor
public class Usershopcart implements Serializable {
    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Integer cropid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private String cropname;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Double cropunit;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Double cosumeramount;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Double cosumerprice;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private String buyer;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usershopcart
     *
     * @mbg.generated Mon Jan 11 22:06:37 CST 2021
     */
    private static final long serialVersionUID = 1L;
}