package com.personal.ecommercesys.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * @TableName userorder
 */
@Data
public class Userorder implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Integer id;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Integer cropid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private String cropname;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Double tradeunit;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Double shopamount;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Double shopallvalue;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private String buyer;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private Date ordercreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userorder
     *
     * @mbg.generated Tue Jan 12 12:03:23 CST 2021
     */
    private static final long serialVersionUID = 1L;
}