package com.personal.ecommercesys.model;

import java.io.Serializable;
import lombok.Data;

/**
 * @TableName userwaiting
 */
@Data
public class Userwaiting implements Serializable {
    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String username;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String gender;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String userpwd;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String telephone;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String address;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String grade;

    /**
     * 
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private String identitycard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userwaiting
     *
     * @mbg.generated Sat Jan 09 21:52:26 CST 2021
     */
    private static final long serialVersionUID = 1L;
}